#!/bin/bash

# Check if an argument is provided
if [ -z "$1" ]; then
  echo "FAIL: provide an argument between 1 and 4."
  exit 1
fi

if [ -z "$2" ]; then
  echo "FAIL: provide a container Name."
  exit 1
fi

# Store the argument
option=$1
container_name=$2

# Display different messages based on the argument
case $option in
  1)
		echo "banner and session files added"
    # Modify the .bashrc file in the container
    cat ~/banner_copy | sudo lxc-attach -n $container_name  -- bash -c 'cat >> /etc/bash.bashrc'

    # Create the startchatbot.sh file
    tar czf - -C ~/ startchatbot.sh | sudo lxc-attach -n $container_name -- tar xzf - -C /usr/

    # Make the chatbothelp script executable
    sudo lxc-attach -n $container_name -- chmod 777 /usr/startchatbot.sh
    # add the session files to /root/session_files
    tar czf - -C ~/ session_files | sudo lxc-attach -n $container_name -- tar xzf - -C /usr/
    ;;
  3)
	  echo "session files added"

		# add the session files to /root/session_files
    tar czf - -C ~/ session_files | sudo lxc-attach -n $container_name -- tar xzf - -C /usr/

    ;;
  2)
		echo "banner added"
    # Modify the .bashrc file in the container
    cat ~/banner_copy | sudo lxc-attach -n $container_name  -- bash -c 'cat >> /etc/bash.bashrc'

    # Create the startchatbot.sh file
    tar czf - -C ~/ startchatbot.sh | sudo lxc-attach -n $container_name -- tar xzf - -C /usr/

    # Make the chatbothelp script executable
    sudo lxc-attach -n $container_name -- chmod 777 /usr/startchatbot.sh
    ;;
  4)
    echo "Nothing added"
    ;;
  *)
    echo "Invalid option. Please choose between 1 and 4."
    ;;
esac
